import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full min-h-screen bg-black text-center text-white">
        <div className="text-7xl pt-20">one-three</div>
        <div className="opacity-50">thirteen three.js experiments</div>

        <div className="w-full max-w-7xl m-auto grid grid-cols-1 lg:grid-cols-2 p-8 gap-8">
          <div className="bg-zinc-900 w-full h-56 flex items-center justify-center flex-col">
            <div className="text-4xl">one</div>
            <div className="opacity-50">coming soon</div>
          </div>

          <div className="bg-zinc-900 w-full h-56 flex items-center justify-center flex-col">
            <div className="text-4xl">two</div>
            <div className="opacity-50">coming soon</div>
          </div>

          <div className="bg-zinc-900 w-full h-56 flex items-center justify-center flex-col">
            <div className="text-4xl">three</div>
            <div className="opacity-50">coming soon</div>
          </div>
          <div className="bg-zinc-900 w-full h-56 flex items-center justify-center flex-col">
            <div className="text-4xl">four</div>
            <div className="opacity-50">coming soon</div>
          </div>

          <div className="bg-zinc-900 w-full h-56 flex items-center justify-center flex-col">
            <div className="text-4xl">five</div>
            <div className="opacity-50">coming soon</div>
          </div>
          <div className="bg-zinc-900 w-full h-56 flex items-center justify-center flex-col">
            <div className="text-4xl">six</div>
            <div className="opacity-50">coming soon</div>
          </div>
          <div className="bg-zinc-900 w-full h-56 flex items-center justify-center flex-col">
            <div className="text-4xl">seven</div>
            <div className="opacity-50">coming soon</div>
          </div>
          <div className="bg-zinc-900 w-full h-56 flex items-center justify-center flex-col">
            <div className="text-4xl">eight</div>
            <div className="opacity-50">coming soon</div>
          </div>

          <div className="bg-zinc-900 w-full h-56 flex items-center justify-center flex-col">
            <div className="text-4xl">nine</div>
            <div className="opacity-50">coming soon</div>
          </div>

          <div className="bg-zinc-900 w-full h-56 flex items-center justify-center flex-col">
            <div className="text-4xl">ten</div>
            <div className="opacity-50">coming soon</div>
          </div>

          <div className="bg-zinc-900 w-full h-56 flex items-center justify-center flex-col">
            <div className="text-4xl">eleven</div>
            <div className="opacity-50">coming soon</div>
          </div>

          <div className="bg-zinc-900 w-full h-56 flex items-center justify-center flex-col">
            <div className="text-4xl">twelve</div>
            <div className="opacity-50">coming soon</div>
          </div>

          <div className="bg-zinc-900 w-full h-56 flex items-center justify-center flex-col">
            <div className="text-4xl">thirteen</div>
            <div className="opacity-50">coming soon</div>
          </div>
        </div>
      </main>
    </>
  );
}
